### ISSUE TITLE
The pattern <State, Color, 'true', Msg> can never match the type <_,99 | 103 | 109 | 114,'false',_>

### ISSUE THREAD

**Issue by Pedro-Giorgiano** [erlware/erlware_commons#173]
Running the dialyzer, i got the following message:

Line 248 Column 1: The pattern <State, Color, 'true', Msg> can never match the type <_,99 | 103 | 109 | 114,'false',_>
Line 253 Column 1: The pattern <State, Color, 'true', Msg> can never match the type <_,99 | 103 | 109 | 114,'false',_>

These messages comming from  erlware_commons/src/ec_cmd_log.erl

Erlang/OTP 26

**Comment by ferd** [comment]
Looks like the file never calls `colorize` with the third value (whether to bold the content) set to `true` _except in a test_, and that test is not part of the full normal compilation. 

We can either remove the test cases and related clauses since the code is unreachable, or export the `colorize` function (even if no one uses it) to make its branch theoretically reachable and get Dialyzer to stop complaining.
