### ISSUE TITLE
Sort out licenses

### ISSUE THREAD

**Issue by hdurer** [erlware/erlware_commons#86]
The README file should spell out the licensing of the code.

Various module seem to be proprietary (i.e. have no OSI approved licensing statement and therefore default to not being usable without violating the copyright).  Ideally, these would be licensed under an open source license or alternatively the proprietary and OS components should be split into separate apps.

**Comment by ericbmerritt** [comment]
The `COPYING` file spells out the licensing of the code quite clearly. I don't see any reason to include it in the readme as well. There is some argument for calling that file `LICENSE` instead of `COPYING` and that's a discussion worth having. 

This packages is quite obviously licensed under the license found in COPYING. So your assumption is incorrect and a bit nonsensical given the COPYING file. If you had happened across the a single file from this package somewhere, it would make more sense. However, I get the impression that you are simply trying to be pedantic here. 

That said, having a one line reference and link to a license might be useful in the situation where someone copies a single file out somewhere, but I am unsure that that is worth the clutter.

**Comment by hdurer** [comment]
I only noticed that some files carry an explicit license notice while others do not and from that concluded that those without are of uncertain licensing status.

I see your point that looking at it in context the COPYING file should be enough and those explicit, within-file licensing statements are just redundant.
